export const VLOGS = 'VLOGS'
export const MY_VLOGS = 'MY_VLOGS'
export const GET_VLOG = 'GET_VLOG'
export const CREATE_VLOG = 'CREATE_VLOG'
export const DELETE_VLOG = 'DELETE_VLOG'
export const LIKE_VLOG = 'LIKE_VLOG'